name: BLOG MAF CONSULTORIA E TREINAMENTO
description: Blogging about stuffs	description: Artigos e Ebooks
meta_description: "Blog da MAF Consultoria e Treinamento com os artigos e ebooks gratuitos."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /kasper
domain_name: "https://ohenriquet.github.io/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://www.linkedin.com/in/ant%C3%B4nio-martiningo-0a4b5978/"
author: "Your Name"	author: "Antonio Martiningo"

# Disqus config
disqus-shortname: ""
