name: BLOG DO ANTONIO
description: Blogging about stuffs
meta_description: "BLOG DO ANTONIO"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /kasper
domain_name: "https://ohenriquet.github.io/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config
disqus-shortname: ""
